Warning cleanups, better RC handling, README

diff --git a/c99sh b/c99sh
--- a/c99sh
+++ b/c99sh
@@ -4,49 +4,44 @@ set -eu
 [ ! -f "$1" ] && echo "File '$1' does not exist"      1>&2 && exit $LINENO
 
 # Automatic cleanup of temporaries named somewhat like input filenames
-cout=$(mktemp "${TMPDIR-/tmp}/c99sh.cout.XXXXXX.c") # Modified source
-xout=$(mktemp "${TMPDIR-/tmp}/c99sh.xout.XXXXXX.x") # Compiled binary
+cout=$(mktemp "${TMPDIR-/tmp}/c99sh.XXXXXX.c") # Mangled source
+xout=$(mktemp "${TMPDIR-/tmp}/c99sh.XXXXXX.x") # Compiled binary
 trap 'rm -f "$cout" "$xout"' EXIT
 
 # Process a possibly non-existent rcfile given its filename
-# TODO Process each file at most once
-# TODO Failed preprocessing stuff pointing to .c99sh file
-: ${LDFLAGS:=} ${CFLAGS:=}
+declare -a flags=(${CFLAGS-} "-I$(dirname "$1")")
+declare -a sources=("$cout" ${LDFLAGS-})
 process_rcfile() {
-    if [ -f "$1" ]; then
-        while read -r line; do
-            if   [[ $line =~ ^[[:space:]]*#                             ]]; then
-                echo "$line" >> "$cout"
-            elif [[ $line =~ ^[[:space:]]*-[lLR]                        ]]; then
-                LDFLAGS+=$line
-                LDFLAGS+=" "
-            elif [[ $line =~ ^[[:space:]]*pkg-config[[:space:]]+--lib   ]]; then
-                LDFLAGS+=$(eval "$(printf %q "$line")")
-                LDFLAGS+=" "
-            elif [[ $line =~ ^[[:space:]]*pkg-config[[:space:]]+--cflag ]]; then
-                CFLAGS+=$( eval "$(printf %q "$line")")
-                CFLAGS+=" "
-            else
-                CFLAGS+=$line
-                CFLAGS+=" "
-            fi
-        done < "$1"
+  [ ! -f "$1" ] && return 0
+  while read -r line; do
+    if   [ -z "$line" ]
+    then :
+    elif [[ $line =~ ^[[:space:]]*# ]]
+    then echo "$line" >> "$cout" # TODO Implicate '#line NNN rcfile'
+    elif [[ $line =~ ^[[:space:]]*-[lLR] ]]
+    then sources+=("$line")
+    elif [[ $line =~ ^[[:space:]]*pkg-config[[:space:]]+--libs ]]
+    then sources+=($(eval "$line")) # FIXME Glaring security bug
+    elif [[ $line =~ ^[[:space:]]*pkg-config[[:space:]]+--cflags ]]
+    then flags+=($(eval "$line")) # FIXME Glaring security concern
+    else flags+=($line)
     fi
+  done < "$1"
 }
 
-# Process all relevant rcfiles
-dirn=$(dirname "$1")
-process_rcfile "$HOME/.c99sh"
-process_rcfile "$dirn/.c99sh"
+# Process any relevant rcfiles
+process_rcfile "$HOME/.c99shrc"
+[ "$PWD" != "$HOME" ] && process_rcfile "$PWD/.c99shrc"
 
 # Prepare source files for "interpretation" by the compiler.
 # Possibly swap shebang on first line of each with a line pragma so
 #   (a) the source can be compiled, and
-#   (b) errors and warnings show usable line numbers.
+#   (b) errors and warnings show usable line details
 echo "#line 1 \"$1\""                 >> "$cout"
 sed "1s|^#!.*\$|#line 2 \"$1\"|" "$1" >> "$cout"
 
 # Compile and execute with any remaining command line arguments
-c99 $CFLAGS -o "$xout" "-I$dirn" "$cout" $LDFLAGS
+c99 -o "$xout" "${flags[@]}" "${sources[@]}"
 shift
+# TODO Can exec be used and the cleanup trap still executed?
 "$xout" "$@"
