Unify error handling

diff --git a/c99sh b/c99sh
--- a/c99sh
+++ b/c99sh
@@ -1,7 +1,9 @@
 #!/bin/bash
 set -eu
-[ $# -lt 1  ] && echo "Use $0 only as an interpreter" 1>&2 && exit $LINENO
-[ ! -f "$1" ] && echo "File '$1' does not exist"      1>&2 && exit $LINENO
+fatal() { status=$1; shift; printf "$@" 1>&2; echo 1>&2; exit $status; }
+[ $# -lt 1  ] && fatal $LINENO "Use %s only as an interpreter" "$0"
+[ ! -f "$1" ] && fatal $LINENO "File '%s' does not exist"      "$1"
+
 
 d=$(dirname "$1")                         # Directory of source
 c=$(mktemp "${TMPDIR-/tmp}/c99sh.XXXXXX") # Mangled source
@@ -29,8 +31,7 @@ process_rcfile() {
     then logic+=($(eval $(printf %q "$o")))
     elif [ -f "$o" ]                      # Linker target
     then logic+=($o)
-    else printf "%s:%s:1 error: invalid c99sh\n\t%s\n\t^\n" "$1" "$i" "$o" 1>&2
-         exit $LINENO
+    else fatal $LINENO "%s:%s:1 error: invalid c99sh\n\t%s\n\t^" "$1" "$i" "$o"
     fi
   done < "$1"
 }
